name: Update ICS calendar file

env:
  ICS_URL: https://calendar.google.com/calendar/ical/info%40hackerspace.gent/public/basic.ics

on:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  merge_new_ics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: Download latest ICS file
        run: |
          echo curl -v -O calendar.ics "$ICS_URL"
          curl "$ICS_URL" > calendar.ics
      - uses: stefanzweifel/git-auto-commit-action@v4